version:  '3'
services:
  polymath:
     image: "joequant/polymath"
     stdin_open: true
     tty: true
     user: user
     command: "/bin/bash"
     working_dir: /home/user
     volumes:
       - user-volume:/home/user
     depends_on:
       - ganache-cli
  ganache-cli:
     image: trufflesuite/ganache-cli:v6.2.5
     command: /usr/bin/ganache-cli -l 1000000000

volumes:
   user-volume:
     external: true
