version:  '3'
services:
  polymath:
     image: "joequant/polymath"
     stdin_open: true
     tty: true
     volumes:
       - home:/home
     depends_on:
       - ganache-cli
  ganache-cli:
     image: trufflesuite/ganache-cli
     command: /usr/bin/ganache-cli -l 1000000000
     ports:
       - "8545:8545"
volumes:
   home:
