version: '3'
services:
#  graph-node:
#    image: graphprotocol/graph-node
#    ports:
#      - "8000:8000"
#      - "8001:8001"
#      - "8020:8020"
#    depends_on:
#      - ipfs
#      - postgres
#    environment:
#      postgres_host: postgres
#      postgres_user: graph-node
#      postgres_pass: let-me-in
#      postgres_db: graph-node
#      ipfs: "ipfs:5001"
#      ethereum: "mainnet:https://mainnet.infura.io"
  ipfs:
# see https://discuss.ipfs.io/t/getting-a-405-method-not-allowed-error-in-the-latest-go-ipfs-docker-image/7665
    image:  ipfs/go-ipfs:master-2020-03-13-6774106 
    ports:
      - "5001:5001"
    volumes:
      - ./data/ipfs:/data/ipfs
#  postgres:
#    image: postgres
#    ports:
#      - "5432:5432"
#    environment:
#      POSTGRES_USER: graph-node
#      POSTGRES_PASSWORD: let-me-in
#      POSTGRES_DB: graph-node
#    volumes:
#      - ./data/postgres:/var/lib/postgresql/data
  geth:
    image: ethereum/client-go
    ports:
      - "8545:8545"
      - "8546:8546"
      - "3030:3030"
    volumes:
      - ./data/ethereum:/root/.ethereum
    command: >
      --http  --http.api web3,eth,personal,miner,net,txpool
      --http.addr "127.0.0.1" --graphql --cache=2048
      --txpool.globalqueue=1000000
