version:  '3'
services:
  blocksci-server:
     build: ./blocksci-server/
     image: "joequant/blocksci-server"
     command: /root/startup.sh
     volumes:
       - bitcoin-data:/var/lib/bitcoin
       - blocksci-data:/var/lib/blocksci

  bitcoind:
     build: ./bitcoind/
     image: "joequant/bitcoind"
     user: bitcoin
     command: "/usr/bin/bitcoind -datadir=/var/lib/bitcoin -pid=/run/bitcoin/bitcoin.pid -conf=/etc/bitcoin.conf"
     volumes:
       - bitcoin-data:/var/lib/bitcoin

volumes:
     bitcoin-data:
        driver: local
        driver_opts:
          type: none
          o: bind
          device: ${DIR}/bitcoin
     blocksci-data:
        driver: local
        driver_opts:
          type: none
          o: bind
          device: ${DIR}/blocksci
