version:  '3'
services:
  blocksci-server:
     stdin_open: true
     tty: true
     command: /bin/bash
     build: ./blocksci-server/
     image: "joequant/blocksci-server"
     volumes:
       - bitcoin-data:/var/lib/bitcoin

  bitcoind:
     build: ./bitcoind/
     image: "joequant/bitcoind"
     command: "sudo -u bitcoin /usr/bin/bitcoind -datadir=/var/lib/bitcoin -pid=/run/bitcoin/bitcoin.pid -conf=/etc/bitcoin.conf"
     volumes:
       - bitcoin-data:/var/lib/bitcoin

volumes:
     bitcoin-data:



