version:  '3'
services:
  blocksci-server:
     build: ./blocksci-server/
     image: "joequant/blocksci-server"
     command: /root/apps/startup.sh
     ports:
       - 18812:18812
       - 5000:5000
     volumes:
       - bitcoin-data:/var/lib/bitcoin
       - blocksci-data:/var/lib/blocksci
       - apps:/root/apps

  bitcoind:
     build: ./bitcoind/
     image: "joequant/bitcoind"
     user: bitcoin
     command: "/usr/bin/bitcoind -datadir=/var/lib/bitcoin -pid=/run/bitcoin/bitcoin.pid -conf=/etc/bitcoin.conf --txindex=1 --dbcache=8000"
     volumes:
       - bitcoin-data:/var/lib/bitcoin

volumes:
     bitcoin-data:
        driver: local
        driver_opts:
          type: none
          o: bind
          device: ${DIR}/bitcoin
     blocksci-data:
        driver: local
        driver_opts:
          type: none
          o: bind
          device: ${DIR}/blocksci
     apps:
        driver: local
        driver_opts:
          type: none
          o: bind
          device: ${DIR}/apps
